# Generated by Django 4.2.3 on 2023-07-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0008_auto_20170515_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='job_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
