# Generated by Django 4.2.3 on 2023-07-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0009_signature_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('affiliation', models.CharField(max_length=200, null=True)),
                ('job_title', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
