# Generated by Django 4.2.3 on 2023-07-15 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0010_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='petition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='petitions.petition'),
            preserve_default=False,
        ),
    ]
