# Generated by Django 4.2.3 on 2023-07-15 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0011_suggestion_petition'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
